version: '3.8'

services:
  app:
    image: test-app:latest # your image name
    volumes:
      - ./src/assets/file:/app/assets/file # example of mounting file to container
    ports:
      - "3000:3000"